reputation_strategy: "ReputationWeightedAverage"
agents:
    - amount: 10
      distort_strategy: "DistortDoNothingStrategy"
      rate_strategy: "RateHigherHalfRandom"
    - amount: 20
      distort_strategy: "DistortUpByOneRandom"
      rate_strategy: "RateRandomStrategy"
