reputation_strategy: "ReputationAverageStrategy"
improvement_handlers:
  # in order of the chain from top to bottom
  # i.e. the topmost is the entry handler
  - "Aging"
  - "StakeBasedReputation"
seed: 10 #leave empty for random
agents:
  - amount: 100
    distort_strategy: "DistortDoNothingStrategy"
    rate_strategy: "RateNearClaimScore"
  - amount: 20
    distort_strategy: "DistortUpByOneRandom"
    rate_strategy: "RateRandomStrategy"
