reputation_strategy: "ReputationWeightedAverage"
improvement_handlers:
  # in order of the chain from top to bottom
  # i.e. the topmost is the entry handler
  - "Aging"
  - "Weights"
  - "StakeBasedReputation"
seed: 10 #leave empty for random
agents:
  - amount: 100
    base_behavior: "HonestClaimer"
    claim_range: [0.5, 1]
    rate_probability: 0.1
  - amount: 20
    distort_strategy: "DistortUpByOneRandom"
    rate_strategy: "RateFromOwnExperience"
    claim_range: [0, 1]
    claim_probability: 0.1
    rate_probability: 0.8
    claim_truth_assessment_inaccuracy: 0.125
metrics:
  - "AvgAccuracyPerRound"
  - "AvgAccuracyPerScenario"
  - "AvgAccuracyPerRound_Another"
  - "AvgTotClaimInaccuracyAndReputationScatter"
